### ISSUE TITLE
About image annotation

### ISSUE THREAD

**Issue by DrexlerChao** [MGHComputationalPathology/slim#32]
Dear Sir,
After upload WSI DICOM image to Slim successfully, we try to annotate ROI.
The image size is under 1G and follow supplement 145 standard.
Some cases enable annotated, but some cases unable annotated.
How to check the root cause that the Slim unable to annotate ROI ?

Any help or suggestion will be sincerely appreciate.
Thanks a lot.

**Comment by hackermd** [comment]
@DrexlerChao thank you for testing Slim and for reporting the issue. Is there an error message in the JavaScript console of the browser?

I have encountered this problem with images that have a wrong image orientation or offset resulting in negative coordinate points. What the values of *Image Orientation Slide* and *X/Y Offset in Slide Coordinate System* in the data sets that cause the error?

**Comment by DrexlerChao** [comment]
@hackermd Thanks for your suggestions. Here is my error message in the JavaScript console of the browser:
map coordinates from pixel matrix to slide coordinate system scoord3dUtils.js:26 
remove ROI 2.25.672764296485173435553631564510971468282 viewer.js:2088 
Uncaught Error: coordinates of Polygon must be positive numbers scoord3d.js:201 
    at new n (scoord3d.js:201)
    at scoord3dUtils.js:44
    at e.value (viewer.js:1634)
    at t.<anonymous> (viewer.js:1538)
    at t.dispatchEvent (Target.js:111)
    at t.finishDrawing (Draw.js:986)
    at t.handleUpEvent (Draw.js:637)
    at t.handleEvent (Pointer.js:144)
    at t.handleEvent (Draw.js:570)
    at t.handleMapBrowserEvent (PluggableMap.js:1031)
n @ scoord3d.js:201
(anonymous) @ scoord3dUtils.js:44
value @ viewer.js:1634
(anonymous) @ viewer.js:1538
t.dispatchEvent @ Target.js:111
t.finishDrawing @ Draw.js:986
t.handleUpEvent @ Draw.js:637
t.handleEvent @ Pointer.js:144
t.handleEvent @ Draw.js:570
t.handleMapBrowserEvent @ PluggableMap.js:1031
t.dispatchEvent @ Target.js:111
t.handlePointerUp_ @ MapBrowserEventHandler.js:197

My Image Orientation Slide:
0048,0102 (ImageOrientationSlide): -1\0\0\0\-1\0

My X/Y Offset in Slide Coordinate System:
0040,072a (XOffsetInSlideCoordinateSystem): 21.69249
0040,073a (YOffsetInSlideCoordinateSystem): 3.915836

Hopefully, the error message and DICOM tages information can figure out the root cause.
Thanks for your help.

**Comment by DrexlerChao** [comment]
@hackermd Hi Sir,
I add the other case which Slim enable annotation.
The Image Orientation Slide:
0048,0102 (ImageOrientationSlide): -1\0\0\0\-1\0

The X/Y Offset in Slide Coordinate System:
0040,072a (XOffsetInSlideCoordinateSystem): 12.30691
0040,073a (YOffsetInSlideCoordinateSystem): 20.76015

For your reference.
Thanks a lot.

**Comment by hackermd** [comment]
It appears that the value of the Image Orientation Slide attribute is wrong. That is an issue we encountered before.

Here is my take on the value set that is compliance with the standard.

![ImageOrientationSlide](https://user-images.githubusercontent.com/6855297/124641401-aade8780-de5c-11eb-9afe-7b8160b2670a.png)

Unfortunately, there is not much Slim can do about it. We could allow negative coordinates, but in the case of slide microscopy imaging, negative coordinates are not allowed by the standard, since the specimen is supposed to reside on the slide.

**Comment by DrexlerChao** [comment]
@hackermd Dear Sir,
We use 3DHISTECH to scan WSI and 3DHISTECH's Slide Converter tool convert mrxs file to DICOM file.
Because of default setting, the values of Image Orientation Slide as follow,
![tag](https://user-images.githubusercontent.com/27002631/125036269-643f9600-e0c5-11eb-9183-e94786be99af.png)

As you mentioned, the Image Orientation Slide attribute is wrong.
But some cases able to annotate, as follow,
![enable](https://user-images.githubusercontent.com/27002631/125037206-6bb36f00-e0c6-11eb-9b55-7e63f022d046.png)

One case able to annotate partially, as follow,
![example](https://user-images.githubusercontent.com/27002631/125037440-ba610900-e0c6-11eb-9807-bb3cf715f794.png)

Unfortunately, a lot of cases unable to annotate.
The different result quite interesting, if the values of Image Orientation Slide attribute is wrong.

We need the help from 3DHISTECH to adjust the Image Orientation Slide attribute.
At the same time, if you have any further suggestion that we can fix the issue, that would be awesome.
Thanks for your help.

**Comment by hackermd** [comment]
Thanks @DrexlerChao for the additional information. The reason why some regions can be annotated and other cannot is due to their position on the slide relative to the SLIDE_CORNER. The Slim viewer translates  image (Row, Column) coordinates into slide (X, Y, Z) coordinates and throws an error if slide coordinates have negative values for X or Y, which would indicate that the annotated region would be located outside of the slide.

Here is an example using [highdicom](https://github.com/MGHComputationalPathology/highdicom) to illustrate the problem:

```python
import numpy as np
from highdicom.spatial import ImageToReferenceTransformer

transformer = ImageToReferenceTransformer(
    image_position=(20.60062, 4.66424, 0.0),
    image_orientation=(-1.0, 0.0, 0.0, 0.0, -1.0, 0.0),
    pixel_spacing=(0.0834033, 0.0832901)
)
image_coordinates = np.array([
    [1.0, 1.0],
    [10.0, 10.0],
    [100.0, 100.0],
])
slide_coordinates = transformer(image_coordinates)
print(slide_coordinates)
```

You can see how the slide coordinates move off the slide with increasing image coordinates (in Slim the image is oriented such that the SLIDE_CORNER is in the upper left corner of the viewport):

```python
[[ 20.5173299   4.5808367   0.       ]
 [ 19.767719    3.830207    0.       ]
 [ 12.27161    -3.67609     0.       ]]
```

I would recommend notifying 3DHISTECH about the issue. In the meantime, you can try to fix the value of the Image Orientation Slide in the image data sets manually. For example using pydicom:

```python
from pydicom import dcmread

ds = dcmread(...)
ds.ImageOrientationSlide = [-1., 0., 0., 0., 1., 0.]
ds.save(...)
```

This should fix the transformation and result in correct slide coordinates:

```python
import numpy as np
from highdicom.spatial import ImageToReferenceTransformer

transformer = ImageToReferenceTransformer(
    image_position=(20.60062, 4.66424, 0.0),
    image_orientation=(-1.0, 0.0, 0.0, 0.0, 1.0, 0.0),
    pixel_spacing=(0.0834033, 0.0832901)
)
image_coordinates = np.array([
    [1.0, 1.0],
    [10.0, 10.0],
    [100.0, 100.0],
])
slide_coordinates = transformer(image_coordinates)
print(slide_coordinates)
```

```python
[[ 20.5173299   4.7476433   0.       ]
 [ 19.767719    5.498273    0.       ]
 [ 12.27161    13.00457     0.       ]]
```

**Comment by DrexlerChao** [comment]
@hackermd Dear Sir,
Thanks for clearly description and kindly response.
After modify Image Orientation Slide attribute to [-1.0, 0.0, 0.0, 0.0, 1.0, 0.0], the Slim can annotate ROI as follow,
![3DHISTECH_slim_annotate](https://user-images.githubusercontent.com/27002631/125419886-c4513fb2-f834-4066-b63f-91e0b9cb89d3.png)

If 3DHISTECH unable to change the Image Orientation Slide attribute, we are going to fix the value manually.
Thanks for your great help and support.
